/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.virgenmilagrosa.presentacion;

import com.virgenmilagrosa.logicanegocio.gestionalumnos.Alumno_LN;
import com.virgenmilagrosa.logicanegocio.gestionalumnos.Apoderado_LN;
import com.virgenmilagrosa.presentacion.gestionalumnos.FrmModificarAlumno;
import com.virgenmilagrosa.presentacion.gestionalumnos.FrmRegistroAlumnos;
import com.virgenmilagrosa.tranversal.control.Validaciones;
import com.virgenmilagrosa.tranversal.entidades.Alumnos;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucho
 */
public class FrmInterfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmInterfazPrincipal
     */
    private int rol;

    public FrmInterfazPrincipal(int rol) {
        this.rol = rol;
        initComponents();
        desactivarBotones(rol);
        
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuOpciones = new javax.swing.JPopupMenu();
        btnActualizar = new javax.swing.JMenuItem();
        btnEliminar = new javax.swing.JMenuItem();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnlUsuarios = new javax.swing.JPanel();
        pnlPagos = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlSecciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        pnlAlumnos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltabla = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnAddAlumno = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlumnos = new javax.swing.JMenu();
        btnMostrarAlumnos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnMostrarSecciones = new javax.swing.JMenuItem();
        btnAumentarVac = new javax.swing.JMenuItem();
        menuMatricula = new javax.swing.JMenu();
        btnGenerarMatricula = new javax.swing.JMenuItem();
        btnGenerarActa = new javax.swing.JMenuItem();

        btnActualizar.setText("Modificar Alumno");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        menuOpciones.add(btnActualizar);

        btnEliminar.setText("Eliminar Alumno");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        menuOpciones.add(btnEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestion de Matricula");
        setBackground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnlUsuariosLayout = new javax.swing.GroupLayout(pnlUsuarios);
        pnlUsuarios.setLayout(pnlUsuariosLayout);
        pnlUsuariosLayout.setHorizontalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );
        pnlUsuariosLayout.setVerticalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        jLayeredPane1.add(pnlUsuarios, "card4");

        javax.swing.GroupLayout pnlPagosLayout = new javax.swing.GroupLayout(pnlPagos);
        pnlPagos.setLayout(pnlPagosLayout);
        pnlPagosLayout.setHorizontalGroup(
            pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );
        pnlPagosLayout.setVerticalGroup(
            pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        jLayeredPane1.add(pnlPagos, "card5");

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logovm.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLayeredPane1.add(pnlPrincipal, "card6");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listado de Secciones");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Tutor", "Grado", "Salon", "Actualizar", "Eliminar"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Buscar");

        jButton2.setText("Añadir Seccion");

        jButton6.setText("Volver al Menu Principal");

        javax.swing.GroupLayout pnlSeccionesLayout = new javax.swing.GroupLayout(pnlSecciones);
        pnlSecciones.setLayout(pnlSeccionesLayout);
        pnlSeccionesLayout.setHorizontalGroup(
            pnlSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeccionesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSeccionesLayout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSeccionesLayout.createSequentialGroup()
                        .addGroup(pnlSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSeccionesLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlSeccionesLayout.setVerticalGroup(
            pnlSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(pnlSecciones, "card2");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Listado de alumnos");

        tbltabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Grado", "Datos del apoderado", "Actualizar", "Eliminar"
            }
        ));
        tbltabla.setComponentPopupMenu(menuOpciones);
        tbltabla.setRowHeight(25);
        jScrollPane2.setViewportView(tbltabla);

        txtBuscar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBuscarCaretUpdate(evt);
            }
        });

        jButton3.setText("Buscar");

        btnAddAlumno.setText("Añadir Alumno");
        btnAddAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAlumnoActionPerformed(evt);
            }
        });

        jButton5.setText("Volver al Menu Principal");

        javax.swing.GroupLayout pnlAlumnosLayout = new javax.swing.GroupLayout(pnlAlumnos);
        pnlAlumnos.setLayout(pnlAlumnosLayout);
        pnlAlumnosLayout.setHorizontalGroup(
            pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlumnosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlumnosLayout.createSequentialGroup()
                        .addComponent(txtBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAlumnosLayout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlAlumnosLayout.setVerticalGroup(
            pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLayeredPane1.add(pnlAlumnos, "card3");

        menuAlumnos.setText("Gestion de Alumnos");
        menuAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlumnosActionPerformed(evt);
            }
        });

        btnMostrarAlumnos.setText("Mostrar alumnos");
        btnMostrarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAlumnosActionPerformed(evt);
            }
        });
        menuAlumnos.add(btnMostrarAlumnos);

        jMenuBar1.add(menuAlumnos);

        jMenu2.setText("Gestión de Secciones");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        btnMostrarSecciones.setText("Mostrar Secciones");
        btnMostrarSecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSeccionesActionPerformed(evt);
            }
        });
        jMenu2.add(btnMostrarSecciones);

        btnAumentarVac.setText("Aumentar Vacantes");
        jMenu2.add(btnAumentarVac);

        jMenuBar1.add(jMenu2);

        menuMatricula.setText("Matricula");

        btnGenerarMatricula.setText("Generar Matrícula");
        menuMatricula.add(btnGenerarMatricula);

        btnGenerarActa.setText("Generar Acta de Compromiso");
        menuMatricula.add(btnGenerarActa);

        jMenuBar1.add(menuMatricula);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlumnosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuAlumnosActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void desactivarBotones(int rol) {
        if (rol == 1) {
            btnAumentarVac.setVisible(false);
        } else if (rol == 2) {
            menuAlumnos.setVisible(false);
            menuMatricula.setVisible(false);
            btnMostrarSecciones.setVisible(false);
        }
    }
    private void btnMostrarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAlumnosActionPerformed
        // TODO add your handling code here:
        pnlSecciones.setVisible(false);
        pnlPagos.setVisible(false);
        pnlAlumnos.setVisible(true);
        pnlUsuarios.setVisible(false);
    }//GEN-LAST:event_btnMostrarAlumnosActionPerformed

    private void btnMostrarSeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSeccionesActionPerformed
        // TODO add your handling code here:
        pnlSecciones.setVisible(true);
        pnlPagos.setVisible(false);
        pnlAlumnos.setVisible(false);
        pnlUsuarios.setVisible(false);
    }//GEN-LAST:event_btnMostrarSeccionesActionPerformed

    private void txtBuscarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBuscarCaretUpdate
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_txtBuscarCaretUpdate

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
         int fila = tbltabla.getSelectedRow();
        if (fila > -1) {
            
            int codAlumno = (Integer) tbltabla.getValueAt(fila, 0);
            Alumnos alumno = Alumno_LN.getInstance().buscarAlumno(codAlumno);
            
            java.awt.EventQueue.invokeLater(() -> {
                new FrmModificarAlumno(alumno).setVisible(true);
            });

        } else {
            JOptionPane.showMessageDialog(null, "Debe elegir un elemento de la tabla", "Incorrecto", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAddAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAlumnoActionPerformed
        // TODO add your handling code here:
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmRegistroAlumnos().setVisible(true);
        });
    }//GEN-LAST:event_btnAddAlumnoActionPerformed

    // <editor-fold defaultstate="collapsed" desc="Panel Alumnos">  
    
    private DefaultTableModel modelo;
    private Alumno_LN alumno= Alumno_LN.getInstance();
    private Apoderado_LN apad= Apoderado_LN.getInstance();
    private boolean consultar= false;
    private FrmRegistroAlumnos registro;
    private int id = 0;
    
    public void CargarTabla(DefaultTableModel modelo, List<Alumnos> total, JTable tabla) {

        total = this.alumno.listarAlumnos();
        Object fila[] = new Object[8];

        for (int i = 0; i < total.size(); i++) {
            fila[0] = total.get(i).getCodAlu();
            fila[1] = total.get(i).getaPaternoAlu();
            fila[2] = total.get(i).getNombreAlu();
            fila[3] = total.get(i).getaMaternoAlu();
            fila[4] = total.get(i).getTelefonoAlu();
            fila[5] = total.get(i).getEmailAlu();
            fila[6] = total.get(i).getDireccionAlu();
            fila[7] = total.get(i).getCodApoderado();
            modelo.addRow(fila);
        }
        tabla.updateUI();
    }

    public void buscar() {
        String buscar = txtBuscar.getText();

        if (buscar.isEmpty()) {
            actualizarTabla();
        } else if (!buscar.isEmpty()) {

            while (modelo.getRowCount() > 0) {
                modelo.removeRow(0);
            }

            Alumnos alu = alumno.buscarAlumno(Integer.parseInt(buscar));
            List<Alumnos> lista = Collections.singletonList(alu);
            CargarTabla(modelo, lista, tbltabla);
        }

    }

    public void MostrarLista(DefaultTableModel modelo, JTable tabla) {
        List<Alumnos> lista = alumno.listarAlumnos();
        CargarTabla(modelo, lista, tabla);
    }

    public void actualizarTabla() {
        //limpiar tabla

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        //actualiza y cargando
        MostrarLista(modelo, tbltabla);
    }
    
    private void init() {
        setLocationRelativeTo(null);
        Validaciones validaciones = new Validaciones();
        validaciones.ValidarSoloNumeros(txtBuscar);
        
        modelo= new DefaultTableModel(){
            //para que las columnas y filas no se editen
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        this.tbltabla.setModel(modelo);
        modelo.addColumn("CODIGO");
        modelo.addColumn("AP. PATERNO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("AP. MATERNO");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("EMAIL");
        modelo.addColumn("DIRECCION");
        modelo.addColumn("APODERADO");
        MostrarLista(modelo,tbltabla);
        tbltabla.getTableHeader().setReorderingAllowed(false);
    }
    //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnActualizar;
    private javax.swing.JButton btnAddAlumno;
    private javax.swing.JMenuItem btnAumentarVac;
    private javax.swing.JMenuItem btnEliminar;
    private javax.swing.JMenuItem btnGenerarActa;
    private javax.swing.JMenuItem btnGenerarMatricula;
    private javax.swing.JMenuItem btnMostrarAlumnos;
    private javax.swing.JMenuItem btnMostrarSecciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenu menuAlumnos;
    private javax.swing.JMenu menuMatricula;
    private javax.swing.JPopupMenu menuOpciones;
    private javax.swing.JPanel pnlAlumnos;
    private javax.swing.JPanel pnlPagos;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSecciones;
    private javax.swing.JPanel pnlUsuarios;
    private javax.swing.JTable tbltabla;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
