/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.virgenmilagrosa.presentacion;

import com.virgenmilagrosa.logicanegocio.gestionalumnos.Alumno_LN;
import com.virgenmilagrosa.logicanegocio.gestionalumnos.Apoderado_LN;
import com.virgenmilagrosa.logicanegocio.gestionsecciones.Seccion_LN;
import com.virgenmilagrosa.presentacion.generarmatricula.FrmGenerarMatricula;
import com.virgenmilagrosa.presentacion.gestionalumnos.FrmModificarAlumno;
import com.virgenmilagrosa.presentacion.gestionalumnos.FrmRegistroAlumnos;
import com.virgenmilagrosa.presentacion.gestionsecciones.FrmAumentarVacante;
import com.virgenmilagrosa.presentacion.gestionsecciones.FrmRegistroSeccion;
import com.virgenmilagrosa.tranversal.control.Validaciones;
import com.virgenmilagrosa.tranversal.entidades.Alumnos;
import com.virgenmilagrosa.tranversal.entidades.Seccion;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucho y lupe :v
 */
public class FrmInterfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmInterfazPrincipal
     */
    private int rol;

    public FrmInterfazPrincipal(int rol) {
        this.rol = rol;
        initComponents();
        desactivarBotones(rol);
        init();
        init0();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        menuOpcionesAlumnos = new javax.swing.JPopupMenu();
        btnActualizarAlumno = new javax.swing.JMenuItem();
        btnEliminarAlumno = new javax.swing.JMenuItem();
        menuOpcionesSeccion = new javax.swing.JPopupMenu();
        ActualizarSeccion = new javax.swing.JMenuItem();
        EliminarSeccion = new javax.swing.JMenuItem();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnlUsuarios = new javax.swing.JPanel();
        pnlPagos = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlSecciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSeccion = new javax.swing.JTable();
        btnAddSeccion = new javax.swing.JButton();
        btnVolverS = new javax.swing.JButton();
        pnlAlumnos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        txtBuscarAlumno = new javax.swing.JTextField();
        btnBuscarAlumno = new javax.swing.JButton();
        btnAddAlumno = new javax.swing.JButton();
        btnVolverA = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlumnos = new javax.swing.JMenu();
        btnMostrarAlumnos = new javax.swing.JMenuItem();
        menuSeccion = new javax.swing.JMenu();
        btnMostrarSecciones = new javax.swing.JMenuItem();
        btnAumentarVac = new javax.swing.JMenuItem();
        menuMatricula = new javax.swing.JMenu();
        btnGenerarMatricula = new javax.swing.JMenuItem();
        btnGenerarActa = new javax.swing.JMenuItem();

        btnActualizarAlumno.setText("Modificar Alumno");
        btnActualizarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarAlumnoActionPerformed(evt);
            }
        });
        menuOpcionesAlumnos.add(btnActualizarAlumno);

        btnEliminarAlumno.setText("Eliminar Alumno");
        menuOpcionesAlumnos.add(btnEliminarAlumno);

        ActualizarSeccion.setText("Actualizar Seccion");
        ActualizarSeccion.setActionCommand("Actualizar ");
        menuOpcionesSeccion.add(ActualizarSeccion);

        EliminarSeccion.setText("Eliminar Seccion");
        menuOpcionesSeccion.add(EliminarSeccion);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestion de Matricula");
        setBackground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnlUsuariosLayout = new javax.swing.GroupLayout(pnlUsuarios);
        pnlUsuarios.setLayout(pnlUsuariosLayout);
        pnlUsuariosLayout.setHorizontalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );
        pnlUsuariosLayout.setVerticalGroup(
            pnlUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        jLayeredPane1.add(pnlUsuarios, "card4");

        javax.swing.GroupLayout pnlPagosLayout = new javax.swing.GroupLayout(pnlPagos);
        pnlPagos.setLayout(pnlPagosLayout);
        pnlPagosLayout.setHorizontalGroup(
            pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );
        pnlPagosLayout.setVerticalGroup(
            pnlPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        jLayeredPane1.add(pnlPagos, "card5");

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logovm.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLayeredPane1.add(pnlPrincipal, "card6");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listado de Secciones");

        tblSeccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblSeccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "SECCION", "GRADO", "NRO_SALON", "NRO_VACANTES"
            }
        ));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, menuOpcionesSeccion, org.jdesktop.beansbinding.ObjectProperty.create(), tblSeccion, org.jdesktop.beansbinding.BeanProperty.create("componentPopupMenu"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(tblSeccion);

        btnAddSeccion.setText("Añadir Seccion");

        btnVolverS.setText("Volver al Menu Principal");

        javax.swing.GroupLayout pnlSeccionesLayout = new javax.swing.GroupLayout(pnlSecciones);
        pnlSecciones.setLayout(pnlSeccionesLayout);
        pnlSeccionesLayout.setHorizontalGroup(
            pnlSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSeccionesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlSeccionesLayout.createSequentialGroup()
                        .addComponent(btnVolverS, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnAddSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        pnlSeccionesLayout.setVerticalGroup(
            pnlSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSeccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSeccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolverS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLayeredPane1.add(pnlSecciones, "card2");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Listado de alumnos");

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Grado", "Datos del apoderado", "Actualizar", "Eliminar"
            }
        ));
        tblAlumnos.setComponentPopupMenu(menuOpcionesAlumnos);
        tblAlumnos.setRowHeight(25);
        jScrollPane2.setViewportView(tblAlumnos);

        btnBuscarAlumno.setText("Buscar");

        btnAddAlumno.setText("Añadir Alumno");
        btnAddAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAlumnoActionPerformed(evt);
            }
        });

        btnVolverA.setText("Volver al Menu Principal");

        javax.swing.GroupLayout pnlAlumnosLayout = new javax.swing.GroupLayout(pnlAlumnos);
        pnlAlumnos.setLayout(pnlAlumnosLayout);
        pnlAlumnosLayout.setHorizontalGroup(
            pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlumnosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlumnosLayout.createSequentialGroup()
                        .addComponent(txtBuscarAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAlumnosLayout.createSequentialGroup()
                        .addComponent(btnVolverA, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlAlumnosLayout.setVerticalGroup(
            pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnVolverA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(pnlAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLayeredPane1.add(pnlAlumnos, "card3");

        menuAlumnos.setText("Gestion de Alumnos");

        btnMostrarAlumnos.setText("Mostrar alumnos");
        btnMostrarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAlumnosActionPerformed(evt);
            }
        });
        menuAlumnos.add(btnMostrarAlumnos);

        jMenuBar1.add(menuAlumnos);

        menuSeccion.setText("Gestión de Secciones");

        btnMostrarSecciones.setText("Mostrar Secciones");
        btnMostrarSecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSeccionesActionPerformed(evt);
            }
        });
        menuSeccion.add(btnMostrarSecciones);

        btnAumentarVac.setText("Aumentar Vacantes");
        btnAumentarVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarVacActionPerformed(evt);
            }
        });
        menuSeccion.add(btnAumentarVac);

        jMenuBar1.add(menuSeccion);

        menuMatricula.setText("Matricula");

        btnGenerarMatricula.setText("Generar Matrícula");
        btnGenerarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarMatriculaActionPerformed(evt);
            }
        });
        menuMatricula.add(btnGenerarMatricula);

        btnGenerarActa.setText("Generar Acta de Compromiso");
        menuMatricula.add(btnGenerarActa);

        jMenuBar1.add(menuMatricula);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void desactivarBotones(int rol) {
        if (rol == 1) {
            btnAumentarVac.setVisible(false);
        } else if (rol == 2) {
            menuAlumnos.setVisible(false);
            menuMatricula.setVisible(false);
            btnMostrarSecciones.setVisible(false);
        }
    }
    private void btnMostrarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAlumnosActionPerformed
        // TODO add your handling code here:
        pnlSecciones.setVisible(false);
        pnlPagos.setVisible(false);
        pnlAlumnos.setVisible(true);
        pnlUsuarios.setVisible(false);
    }//GEN-LAST:event_btnMostrarAlumnosActionPerformed

    private void btnMostrarSeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSeccionesActionPerformed
        // TODO add your handling code here:
        pnlSecciones.setVisible(true);
        pnlPagos.setVisible(false);
        pnlAlumnos.setVisible(false);
        pnlUsuarios.setVisible(false);
    }//GEN-LAST:event_btnMostrarSeccionesActionPerformed

    private void btnActualizarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarAlumnoActionPerformed
        // TODO add your handling code here:
        int fila = tblAlumnos.getSelectedRow();
        if (fila > -1) {

            int codAlumno = (Integer) tblAlumnos.getValueAt(fila, 0);
            Alumnos alumno = Alumno_LN.getInstance().buscarAlumno(codAlumno);

            java.awt.EventQueue.invokeLater(() -> {
                new FrmModificarAlumno(alumno).setVisible(true);
            });

        } else {
            JOptionPane.showMessageDialog(null, "Debe elegir un elemento de la tabla", "Incorrecto", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarAlumnoActionPerformed

    private void btnAddAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAlumnoActionPerformed
        // TODO add your handling code here:
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmRegistroAlumnos().setVisible(true);
        });
    }//GEN-LAST:event_btnAddAlumnoActionPerformed

    private void btnGenerarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarMatriculaActionPerformed
        // TODO add your handling code here:
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGenerarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmGenerarMatricula().setVisible(true);
        });
    }//GEN-LAST:event_btnGenerarMatriculaActionPerformed

    private void btnAumentarVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarVacActionPerformed
        // TODO add your handling code here:
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGenerarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmAumentarVacante().setVisible(true);
        });

    }//GEN-LAST:event_btnAumentarVacActionPerformed
    /**
     * Autor: Yudely Palpán semana 3 cus implmentado, por corregir.
     */

    // <editor-fold defaultstate="collapsed" desc="Panel Seccion">  
    private DefaultTableModel modelo1;
    private Seccion_LN seccion = Seccion_LN.getInstance();

    public void CargarTablaSeccion(DefaultTableModel modelo1, List<Seccion> total, JTable tabla1) {

        total = this.seccion.listarSecciones();
        Object fila[] = new Object[5];

        for (int i = 0; i < total.size(); i++) {
            fila[0] = total.get(i).getCodSeccion();
            fila[1] = total.get(i).getNombreSeccion();
            fila[2] = total.get(i).getNombreGrado();
            fila[3] = total.get(i).getNroSalon();
            fila[4] = total.get(i).getNroVacantes();

            modelo1.addRow(fila);
        }
        tabla1.updateUI();
    }

    public void MostrarListaSeccion(DefaultTableModel modelo1, JTable tabla1) {
        List<Seccion> lista0 = seccion.listarSecciones();
        CargarTablaSeccion(modelo1, lista0, tabla1);

    }

    public void actualizarTablaSeccion() {
        //limpiar tabla1

        while (modelo1.getRowCount() > 0) {
            modelo1.removeRow(0);
        }
        //actualiza y cargando
        MostrarListaSeccion(modelo1, tblSeccion);
    }

    private void init0() {
        setLocationRelativeTo(null);

        modelo1 = new DefaultTableModel() {
            //para que las columnas y filas no se editen
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        this.tblSeccion.setModel(modelo1);
        modelo1.addColumn("CODIGO");
        modelo1.addColumn("SECCION");
        modelo1.addColumn("GRADO");
        modelo1.addColumn("NRO_SALON");
        modelo1.addColumn("NRO_VACANTES");
        MostrarListaSeccion(modelo1, tblSeccion);
        tblSeccion.getTableHeader().setReorderingAllowed(false);
    }

    //</editor-fold>
    /**
     * Autor: Andrés Espinoza semana 2 cus implmentado.
     */
    // <editor-fold defaultstate="collapsed" desc="Panel Alumnos">  
    private DefaultTableModel modelo2;
    private Alumno_LN alumno = Alumno_LN.getInstance();
    private Apoderado_LN apad = Apoderado_LN.getInstance();
    private boolean consultar = false;
    private FrmRegistroAlumnos registro;
    private int id = 0;

    public void CargarTablaAlumnos(DefaultTableModel modelo2, List<Alumnos> total, JTable tabla2) {

        total = this.alumno.listarAlumnos();
        Object fila[] = new Object[8];

        for (int i = 0; i < total.size(); i++) {
            fila[0] = total.get(i).getCodAlu();
            fila[1] = total.get(i).getaPaternoAlu();
            fila[2] = total.get(i).getNombreAlu();
            fila[3] = total.get(i).getaMaternoAlu();
            fila[4] = total.get(i).getTelefonoAlu();
            fila[5] = total.get(i).getEmailAlu();
            fila[6] = total.get(i).getDireccionAlu();
            fila[7] = total.get(i).getCodApoderado();
            modelo2.addRow(fila);
        }
        tabla2.updateUI();
    }

    public void buscar() {
        String buscar = txtBuscarAlumno.getText();

        if (buscar.isEmpty()) {
            actualizarTablaAlumnos();
        } else if (!buscar.isEmpty()) {

            while (modelo2.getRowCount() > 0) {
                modelo2.removeRow(0);
            }

            Alumnos alu = alumno.buscarAlumno(Integer.parseInt(buscar));
            List<Alumnos> lista = Collections.singletonList(alu);
            CargarTablaAlumnos(modelo2, lista, tblAlumnos);
        }

    }

    public void MostrarLista(DefaultTableModel modelo2, JTable tabla2) {
        List<Alumnos> lista = alumno.listarAlumnos();
        CargarTablaAlumnos(modelo2, lista, tabla2);
    }

    public void actualizarTablaAlumnos() {
        //limpiar tabla2

        while (modelo2.getRowCount() > 0) {
            modelo2.removeRow(0);
        }
        //actualiza y cargando
        MostrarLista(modelo2, tblAlumnos);
    }

    private void init() {
        setLocationRelativeTo(null);
        Validaciones validaciones = new Validaciones();
        validaciones.ValidarSoloNumeros(txtBuscarAlumno);

        modelo2 = new DefaultTableModel() {
            //para que las columnas y filas no se editen
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        this.tblAlumnos.setModel(modelo2);
        modelo2.addColumn("CODIGO");
        modelo2.addColumn("AP. PATERNO");
        modelo2.addColumn("NOMBRE");
        modelo2.addColumn("AP. MATERNO");
        modelo2.addColumn("TELEFONO");
        modelo2.addColumn("EMAIL");
        modelo2.addColumn("DIRECCION");
        modelo2.addColumn("APODERADO");
        MostrarLista(modelo2, tblAlumnos);
        tblAlumnos.getTableHeader().setReorderingAllowed(false);
    }
    //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActualizarSeccion;
    private javax.swing.JMenuItem EliminarSeccion;
    private javax.swing.JMenuItem btnActualizarAlumno;
    private javax.swing.JButton btnAddAlumno;
    private javax.swing.JButton btnAddSeccion;
    private javax.swing.JMenuItem btnAumentarVac;
    private javax.swing.JButton btnBuscarAlumno;
    private javax.swing.JMenuItem btnEliminarAlumno;
    private javax.swing.JMenuItem btnGenerarActa;
    private javax.swing.JMenuItem btnGenerarMatricula;
    private javax.swing.JMenuItem btnMostrarAlumnos;
    private javax.swing.JMenuItem btnMostrarSecciones;
    private javax.swing.JButton btnVolverA;
    private javax.swing.JButton btnVolverS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu menuAlumnos;
    private javax.swing.JMenu menuMatricula;
    private javax.swing.JPopupMenu menuOpcionesAlumnos;
    private javax.swing.JPopupMenu menuOpcionesSeccion;
    private javax.swing.JMenu menuSeccion;
    private javax.swing.JPanel pnlAlumnos;
    private javax.swing.JPanel pnlPagos;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSecciones;
    private javax.swing.JPanel pnlUsuarios;
    private javax.swing.JTable tblAlumnos;
    private javax.swing.JTable tblSeccion;
    private javax.swing.JTextField txtBuscarAlumno;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
