/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.virgenmilagrosa.presentacion.gestionsecciones;

import com.virgenmilagrosa.GestionMatriculaConfig;
import com.virgenmilagrosa.logicanegocio.gestionsecciones.Seccion_LN;
import com.virgenmilagrosa.tranversal.entidades.Seccion;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import com.virgenmilagrosa.tranversal.entidades.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Lupita
 */
public class FrmAumentarVacante extends javax.swing.JFrame {

    /**
     * Creates new form AsignarVacante
     */
    private Seccion seccion;

    public FrmAumentarVacante() {
        initComponents();
        MetodoInicio();

    }

    private void MetodoInicio() {
        GestionMatriculaConfig.icon(this);
        Seccion_LN.getInstance().listarSecciones().forEach(
                (item) -> cbxSeccion.addItem(item)
        );
    }

    public void ValidarIngreso() {
        // String nseccion=cbxSeccion.getText().trim();
        String nrovacantes = spnVacantes.getValue().toString();

        if (nrovacantes.isEmpty()) {
            btnAsignar.setEnabled(false);
        } else {
            btnAsignar.setEnabled(true);
        }
    }

    public void actualizarVacantes() {
        int VacantesSec = seccion.getNroVacantes();
        seccion.setNroVacantes((int) spnVacantes.getValue() + VacantesSec);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spnVacantes = new javax.swing.JSpinner();
        cbxSeccion = new javax.swing.JComboBox<Seccion>();
        btnAsignar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asignar Vacante/Volver-Buttom.png"))); // NOI18N
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de seccion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Sección");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 120, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Nro de Vacantes:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 119, -1));

        spnVacantes.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        spnVacantes.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                spnVacantesCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jPanel2.add(spnVacantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 250, -1));

        cbxSeccion.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cbxSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeccionActionPerformed(evt);
            }
        });
        jPanel2.add(cbxSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 400, 24));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 640, 150));

        btnAsignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asignar Vacante/AsignarVacante-Buttom.png"))); // NOI18N
        btnAsignar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsignarMouseClicked(evt);
            }
        });
        jPanel1.add(btnAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, 40));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asignar Vacante/Cancelar-Buttom.png"))); // NOI18N
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, 680, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asignar Vacante/AsignarVacante-Panel.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 700, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spnVacantesCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_spnVacantesCaretPositionChanged
        // TODO add your handling code here:
        this.ValidarIngreso();
    }//GEN-LAST:event_spnVacantesCaretPositionChanged

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnAsignarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarMouseClicked
        // TODO add your handling code here:
        actualizarVacantes();
        String mensaje = Seccion_LN.getInstance().ampliarVacantes(seccion, (int) spnVacantes.getValue());
        if (mensaje.equals("Ampliacion Completada")) {
            JOptionPane.showMessageDialog(rootPane, mensaje);
        } else {
            JOptionPane.showMessageDialog(rootPane, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAsignarMouseClicked

    private void cbxSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeccionActionPerformed
        // TODO add your handling code here:
        Seccion seccionSel = (Seccion) cbxSeccion.getSelectedItem();
        seccion = seccionSel;
        // Luego vamos a coger la propiedad de nro de vacantes de la seccion y la setearemos como valor del
        // spinner

    }//GEN-LAST:event_cbxSeccionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAsignar;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JComboBox<Seccion> cbxSeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner spnVacantes;
    // End of variables declaration//GEN-END:variables
}
